package mindustry.randomizer.enums;

public enum ProgressiveItemType {
    S_GROUND_UNIT_A,
    S_GROUND_UNIT_B,
    S_GROUND_UNIT_C,
    S_AIR_UNIT_A,
    S_AIR_UNIT_B,
    S_NAVAL_UNIT_A,
    S_NAVAL_UNIT_B,
    S_RECONSTRUCTOR,
    E_SHIP_FABROCATOR,
    E_MECH_FABRICATOR,
    E_TANK_REFABRICATOR,
    E_MECH_REFABRICATOR,
    E_SHIP_REFABRICATOR,
    E_PRIME_REFABRICATOR,
    E_TANK_ASSEMBLER,
    E_SHIP_ASSEMBLER,
    E_MECH_ASSEMBLER,


}
